# Generated by Django 3.1.3 on 2021-05-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esal', models.IntegerField(default=0)),
                ('ename', models.CharField(max_length=60)),
                ('hiredate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss', models.IntegerField(default=0)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoreact12.employee')),
            ],
        ),
    ]
