# Generated by Django 3.1.3 on 2021-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Children_Name', models.CharField(max_length=120)),
                ('Children_Id', models.IntegerField()),
                ('Children_Father_Name', models.CharField(max_length=56)),
                ('Children_Mother_Namw', models.CharField(max_length=90)),
                ('Children_Roll_No', models.CharField(max_length=90)),
                ('Children_Aadhar_numner', models.IntegerField()),
            ],
        ),
    ]
